services:
  redpanda:
    image: redpandadata/redpanda:v23.3.15
    container_name: redpanda-broker
    command:
      - redpanda start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
      - redpanda_data:/var/lib/redpanda/data

  redpanda-console:
    image: redpandadata/console:v2.3.3
    container_name: redpanda-console
    depends_on:
      - redpanda
    environment:
      - KAFKA_BROKERS=redpanda:29092
    ports:
      - "8080:8080"
    # Add this if you want to use the config file:
    volumes:
      - ./redpanda-console-config.yml:/etc/console/config.yml

  init-topics:
    image: redpandadata/redpanda:v23.3.15
    depends_on:
      - redpanda
    command: |
      bash -c "
        echo 'Waiting for Redpanda to be ready...'
        sleep 30
        rpk topic create trade-data --brokers redpanda:29092
        rpk topic create rsi-data --brokers redpanda:29092
        echo 'Topics created:'
        rpk topic list --brokers redpanda:29092
      "

volumes:
  redpanda_data: